name: Deploy Flask Backend to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: sof-event-extractor-backend   # TODO: set your App Service name
      PYTHON_VERSION: '3.12'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install backend dependencies
        working-directory: sof-event-extractor/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive backend for deploy
        run: |
          cd sof-event-extractor/backend
          echo "web: gunicorn -w 2 -b 0.0.0.0:8000 app:app" > Procfile
          cd ../..
          echo "Created Procfile for Azure App Service" 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: sof-event-extractor/backend


